name: Déploiement Auto

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Envoyer les fichiers au serveur
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }} # (ex: root ou ubuntu)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/websocket-server" # Le dossier sur ton serveur

      - name: Redémarrer le service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/websocket-server
            sudo systemctl restart websocket
